### ISSUE TITLE
how to use inference.sh

### ISSUE THREAD

**Issue by n0obcoder** [tag-and-generate/tagger-generator#3]
I have made a text file which has a the following sentence in it
`Send me the files`
Now I want this text file to be taken as input and make inference using the pretrained tagger and generator model. But I am not sure what the arguments of the following command means
```
bash scripts/inference.sh {input_file} {jobname}\
                          tagged generated\
                          {handle}\
                          {style_0_label} {style_1_label}\
                          {base_folder} {device}
```

So how exactly do I use this command to make inference of my text file ?  
Thanks in advance ! : )

**Comment by ars22** [comment]
- The file containing the sentence you mentioned must be given the name `{input_file}`. 
- `{jobname}` is simply an identifier to track the inference run. 
- `{handle}` is the model identifier -- when the scripts  `scripts/train_tagger.sh` and `scripts/train_generator.sh` were triggered the models would be dumped in the folder `models/{handle}`.
- `{style_0_label}` same argument as what was used in the data creation step (tagger model uses this to tag data) e.g: `POS`
- `{style_1_label}` same argument as what was used in the data creation step (tagger model uses this to tag data) e.g: `NEG`
- `{base_folder}` is the path to your data folder (`{OUTPATH}` used in data creation step). This is basically the location from where the BPE models would be loaded.
- `{device}` is the gpu id.

**Comment by n0obcoder** [comment]
Hey @ars22!
Thanks a lot. This helps : )

**Comment by n0obcoder** [comment]
@ars22 did you train the tagger and the generator from scratch ? I am asking this because the pre-trained models haven't been released.

**Comment by ars22** [comment]
Yes, the tagger and generator were [trained](https://github.com/tag-and-generate/tagger-generator/tree/master/tag-and-generate-train) using the training data which is itself created using steps outlined in [data_prep](https://github.com/tag-and-generate/tagger-generator/tree/master/tag-and-generate-data-prep).

**Comment by n0obcoder** [comment]
That's a great news :D Looking forward to the release!
Thanks again.
