### ISSUE TITLE
preparing dataset for unimodal style transfer

### ISSUE THREAD

**Issue by n0obcoder** [tag-and-generate/tagger-generator#4]
how do i prepare the polite dataset ? It is a unimodal style transfer   so do i write something like this-

`
python src/run.py --data_pth data/politeness_data/politeness_P_9.tsv --outpath data/tmp_politeness/ --style_0_label P_9 --style_1_label P_9 --is_unimodal True
`
where politeness_P_9.tsv is the tsv with 3 columns- ('txt', 'split', 'style') and style = 'P_9' only

**Comment by madaan** [comment]
Hi @n0obcoder, that's mostly correct, with the following changes:

- style_1_label should be a style free corpus, in this case P_0 or P_1. That dataset would be used to calculate the tags for P_9. 

- You can use the entire data file as is, or filter on the target and contrasting corpus. 

I'm adding these clarifications to the README as well, thanks.

**Comment by n0obcoder** [comment]
Thanks @madaan! The updated README is more helpful now :)
