### ISSUE TITLE
Didn't receive the expected output from inference.sh

### ISSUE THREAD

**Issue by rmadaan3** [tag-and-generate/tagger-generator#5]
[input.txt](https://github.com/tag-and-generate/tagger-generator/files/5147573/input.txt)
[test2_tagger_input.txt](https://github.com/tag-and-generate/tagger-generator/files/5147575/test2_tagger_input.txt)
[test2_output.txt](https://github.com/tag-and-generate/tagger-generator/files/5147577/test2_output.txt)
[test2_tagged.txt](https://github.com/tag-and-generate/tagger-generator/files/5147578/test2_tagged.txt)
[test2_generator_input.txt](https://github.com/tag-and-generate/tagger-generator/files/5147579/test2_generator_input.txt)

I have attached all the files used. I did train the tagger and generator as suggested, used your dataset and labels. I was expecting that I would get polite versions in the test2_output.txt after running the inference.sh file but that was not the case.

Can you explain how to just get polite version of a sentence as output?

Thanks a lot.

**Comment by ars22** [comment]
Hi @rmadaan3, 

We have uploaded our trained models on the politeness dataset (link in README) and when we use that model to run inference on your input file, we get the attached intermediate and final outputs. Not sure why the intermediate outputs that you observed with your model where gibberish, but most likely the model wasn't trained properly. Please let us know if you face issues with the model we uploaded.    

[generator_input.txt](https://github.com/tag-and-generate/tagger-generator/files/5153906/generator_input.txt)
[output.txt](https://github.com/tag-and-generate/tagger-generator/files/5153907/output.txt)
[tagged.txt](https://github.com/tag-and-generate/tagger-generator/files/5153908/tagged.txt)
[tagger_input.txt](https://github.com/tag-and-generate/tagger-generator/files/5153909/tagger_input.txt)

**Comment by rmadaan3** [comment]
Can you also explain how to run it? There could be a possibility of an error on my side.

**Comment by ars22** [comment]
@rmadaan3 the inference script should be able to take the input file and trained model to generate the intermediate and final outputs.  

From README:
~~~
bash scripts/inference.sh input_file jobname tagger_target generator_target dataset src_tag tgt_tag base_folder device
~~~

Where:

- input_file: The input test file which needs to be transferred.
- jobname: Unique identifier for the inference job.
- tagger_target: Target used to train tagger -- argument we pass when we run scripts/train_tagger.sh
- generator_target:  Target used to train generator -- argument we pass when we run scripts/train_generator.sh
- dataset: dataset argument we pass when we train tagger or generator -- used to identify model paths for tagger and generator.
- src_tag: {style_0_label} used to create training data [src style]
- tgt_tag: {style_1_label} used to create training data [tgt style]
- base_folder: The folder in which the data files are stored (argument used in creation of training data)
- device: gpu id

In this particular instance, I used this command:

~~~
bash scripts/inference.sh tagger_input.txt gitissue masked unmasked /model/path/in/this/case/politeness GMASK GMASK location/to/dataset/directory/with/subwords/model/in/it 0
~~~

**Comment by rmadaan3** [comment]
This is the command I'm running: ~/TagAndGenerate/tagger-generator-master/tag-and-generate-train$ bash scripts/inference.sh inp/input.txt test tagged generated new GMASK GMASK ../tag-and-generate-data-prep/data/tmp 0

This is the output: Using BPE
Running BPE on input
Adding eos to the input
Running tagger
loading ../tag-and-generate-data-prep/data/tmp/entagged_parallel.bpe.train ../tag-and-generate-data-prep/data/tmp/entagged_parallel.bpe.dev
Traceback (most recent call last):
  File "src/translate.py", line 132, in <module>
    main()
  File "src/translate.py", line 93, in main
    model.load_state_dict(th.load(args.model_file, map_location="cpu"))
  File "/home/rahul17179/.conda/envs/taggen/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Transformer:
	size mismatch for embeds.weight: copying a param with shape torch.Size([15762, 512]) from checkpoint, the shape in current model is torch.Size([657, 512]).
	size mismatch for logits.weight: copying a param with shape torch.Size([15762, 512]) from checkpoint, the shape in current model is torch.Size([657, 512]).
	size mismatch for logits.bias: copying a param with shape torch.Size([15762]) from checkpoint, the shape in current model is torch.Size([657]).
sed: can't read experiments//test_tagged: No such file or directory
Running BPE on masked output
scripts/inference.sh: line 118: experiments//test_tagged: No such file or directory
awk: fatal: cannot open file `experiments//test_generator_input' for reading (No such file or directory)
Running generator
loading ../tag-and-generate-data-prep/data/tmp/engenerated_parallel.bpe.train ../tag-and-generate-data-prep/data/tmp/engenerated_parallel.bpe.dev
Traceback (most recent call last):
  File "src/translate.py", line 132, in <module>
    main()
  File "src/translate.py", line 93, in main
    model.load_state_dict(th.load(args.model_file, map_location="cpu"))
  File "/home/rahul17179/.conda/envs/taggen/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Transformer:
	size mismatch for embeds.weight: copying a param with shape torch.Size([15785, 512]) from checkpoint, the shape in current model is torch.Size([657, 512]).
	size mismatch for logits.weight: copying a param with shape torch.Size([15785, 512]) from checkpoint, the shape in current model is torch.Size([657, 512]).
	size mismatch for logits.bias: copying a param with shape torch.Size([15785]) from checkpoint, the shape in current model is torch.Size([657]).
sed: can't read experiments//test_output: No such file or directory
Traceback (most recent call last):
  File "/home/rahul17179/.conda/envs/taggen/bin/sacrebleu", line 8, in <module>
    sys.exit(main())
  File "/home/rahul17179/.conda/envs/taggen/lib/python3.6/site-packages/sacrebleu.py", line 1740, in main
    for lineno, line in enumerate(smart_open(ref_file, encoding=args.encoding), 1):
  File "/home/rahul17179/.conda/envs/taggen/lib/python3.6/site-packages/sacrebleu.py", line 923, in smart_open
    return open(file, mode=mode, encoding=encoding, newline="\n")
FileNotFoundError: [Errno 2] No such file or directory: 'experiments//test_output'

I prepared the data like in the readme file. I think but you trained differently or either you used different data initially or both. Can you also send the data prep files through which you got the output I desired and also a small guide on how your prepared these data files?

**Comment by ars22** [comment]
I think the correct vocabulary isn't being generated and that's why you observe a size mismatch in embedding weights. Please ensure that "../tag-and-generate-data-prep/data/tmp" argument points to the correct ```base_folder``` which has all the train/dev/test data files that were generated from the data-preparation step.

**Comment by rmadaan3** [comment]
I think that's not the issue, the data files were prepared according to your readme only. That's why I suggested uploading data prep files also.

**Comment by ars22** [comment]
Hi @rmadaan3,

For your convenience, we have created a more detailed tutorial [here](https://github.com/tag-and-generate/tagger-generator), outlining all the steps in sequence. Hopefully, this helps to resolve your issue :)
